version: '3.6'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis: # docker exec -it <container-id> redis-cli (to view redis data)
    image: redis
    restart: always
    ports:
      - 6379:6379
